version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest

commands:
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/workspace

  npm-install:
    steps:
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  lint:
    steps:
      - run:
          name: eslint
          command: npm run lint
  test:
    steps:
      - run:
          name: test
          command: echo "exec test"
  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "03:ac:47:7b:6b:ba:89:86:1d:69:95:14:b8:eb:d5:44"
            - "ee:a9:53:d9:92:7f:f1:9b:6a:e6:6d:50:45:4c:ff:45"
            - "97:51:1f:b4:dc:06:3c:a8:af:f5:8d:b3:8d:3d:c3:b8"
      - run:
          name: Set up git.
          command: |
            git config --global user.name "takeokunn"
            git config --global user.email "bararararatty@gmail.com"
      - run:
          name: webpack build
          command: npm run build
      - run:
          name: deploy staging
          command: npm run deploy

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - npm-install
      - persist-workspace
  lint:
    executor:
      name: default
    steps:
      - attach-workspace
      - lint
  test:
    executor:
      name: default
    steps:
      - attach-workspace
      - test
  deploy:
    executor:
      name: default
    steps:
      - attach-workspace
      - deploy

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
