version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest

commands:
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/workspace

  npm-install:
    steps:
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  lint:
    steps:
      - run:
          name: eslint
          command: npm run lint
  test:
    steps:
      - run:
          name: test
          command: echo "exec test"
  deploy:
    steps:
      - run:
          name: Set up git.
          command: |
            git config --global user.name "takeokunn"
            git config --global user.email "bararararatty@gmail.com"
      - run:
          name: ssh-keyscsan
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: webpack build
          command: npm run build
      - run:
          name: deploy staging
          command: npm run deploy

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - npm-install
      - persist-workspace
  lint:
    executor:
      name: default
    steps:
      - attach-workspace
      - lint
  test:
    executor:
      name: default
    steps:
      - attach-workspace
      - test
  deploy:
    executor:
      name: default
    steps:
      - attach-workspace
      - deploy

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
